# 课堂练习

首先创建一个二维数组,3行4列。

每列为一门学科成绩：语文 数学 英语 化学，如下所示

```
data=np.array([[76, 27, 93, 67],
               [96, 57, 83, 42],
               [56, 35, 93, 88]])

```

- 练习要求：
    1. 求出每人的总成绩
    2. 求出每科的平均成绩
    3. 求出语文的最低分和最高分
    4. 求出每人的文理总分
        - 文科:语文和英语
        - 理科:数据和化学
    5. 如果分数小于60,将分数变为'不及格'
    6. 如果分数小于60,将分数变为'不及格',60~85的分数变为‘良好’,大于85的分数变为‘优秀’



In [1]:
import numpy as np
data=np.array([[76, 27, 93, 67],
               [96, 57, 83, 42],
               [56, 35, 93, 88]])


### 答案书写如下

In [3]:
# 1. 求出每人的总成绩
np.sum(data,axis=1)

array([263, 278, 272])

In [6]:
# 2. 求出每科的平均成绩,小数点后2位
np.round(np.mean(data,axis=0),2)

array([76.  , 39.67, 89.67, 65.67])

In [9]:
# 3. 求出语文的最低分和最高分
np.min(data[:,0])
np.max(data[:,0])

np.int64(96)

In [13]:
# 4. 求出每人的文理总分
#     - 文科:语文和英语
np.sum(data[:,::2],axis=1)
data[:,::2].sum(axis=1)

array([169, 179, 149])

In [23]:
#     - 理科:数据和化学
data[:,1::2].sum(axis=1)

array([ 94,  99, 123])

In [24]:
# 5. 如果分数小于60,将分数变为'不及格'
np.where(data<60,'不及格',data)

array([['76', '不及格', '93', '67'],
       ['96', '不及格', '83', '不及格'],
       ['不及格', '不及格', '93', '88']], dtype='<U21')

In [22]:
# 6. 如果分数小于60,将分数变为'不及格',60~85的分数变为‘良好’,大于85的分数变为‘优秀’
np.where(data<60,'不及格',np.where(data<85,'良好','优秀'))

array([['良好', '不及格', '优秀', '良好'],
       ['优秀', '不及格', '良好', '不及格'],
       ['不及格', '不及格', '优秀', '优秀']], dtype='<U3')