#  pandas之DataFrame数据帧

In [7]:
import pandas as pd
import numpy as np

In [7]:
# 创建 DateFrame
df1 = pd.DataFrame(
    data,  # 二维数据
    index=row_index,  # 行索引标签
    columns=col_index  # 列标签
)
df1

语文  数学  英语  物理
2001  62  30  99  88
2002  68  78  87  44
2003  60  65  38  87
2004  99  96  28  31
2005  54  59   1  85
2006  51  90  33  88

In [17]:
print('df1的形状',df1.shape)
print('df1的维度',df1.ndim)
print('df1的行索引',df1.index)
print('df1的列名称',df1.columns)
print('df1的值\n',df1.values)
print('df1的数据类型:\n',df1.dtypes)

df1的形状 (6, 4)
df1的维度 2
df1的行索引 Index(['2001', '2002', '2003', '2004', '2005', '2006'], dtype='object')
df1的列名称 Index(['语文', '数学', '英语', '物理'], dtype='object')
df1的值
 [[62 30 99 88]
 [68 78 87 44]
 [60 65 38 87]
 [99 96 28 31]
 [54 59  1 85]
 [51 90 33 88]]
df1的数据类型:
 语文    int32
数学    int32
英语    int32
物理    int32
dtype: object


In [22]:
type(df1.values)

numpy.ndarray